import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";

const artifactsDir = requiredEnv("AWR_ARTIFACTS_DIR");
const workspaceDir = requiredEnv("AWR_WORKSPACE_DIR");
const runId = requiredEnv("AWR_RUN_ID");
const workflowName = process.env.AWR_SYSTEM_DEV_WORKFLOW_NAME?.trim() || "System Dev";

const branch = readJson(path.join(artifactsDir, "branch.json"));
const validation = readJsonIfExists(path.join(artifactsDir, "validation.json"));
const e2e = readJsonIfExists(path.join(artifactsDir, "e2e.json"));
const implementationPlan = readJsonIfExists(path.join(artifactsDir, "implementation_plan.json"));

const branchName = requiredField(branch, "branch_name");
const taskName = requiredField(branch, "task_name");
const baseBranch = branch.base_branch || "dev";
const prTitle = buildTitle(branch.branch_prefix || "change", taskName);
const prBodyPath = path.join(artifactsDir, "pr_body.md");
const prJsonPath = path.join(artifactsDir, "pr.json");
const prMdPath = path.join(artifactsDir, "pr.md");

const currentBranch = run("git", ["branch", "--show-current"]).stdout.trim();
if (currentBranch !== branchName) {
  throw new Error(`Current branch is ${currentBranch || "(detached)"}, expected ${branchName}`);
}

const statusBeforeCommit = run("git", ["status", "--porcelain"]).stdout.trim();
let commitCreated = false;
let commitSha = null;

if (statusBeforeCommit !== "") {
  run("git", ["add", "-A"]);
  const stagedDiff = run("git", ["diff", "--cached", "--name-only"]).stdout.trim();
  if (stagedDiff !== "") {
    run("git", ["commit", "-m", prTitle, "-m", `Generated by awr run ${runId}.`]);
    commitCreated = true;
    commitSha = run("git", ["rev-parse", "HEAD"]).stdout.trim();
  }
}

const aheadCount = Number(run("git", ["rev-list", "--count", `${baseBranch}..HEAD`]).stdout.trim());
if (!Number.isFinite(aheadCount) || aheadCount <= 0) {
  throw new Error(`No commits ahead of ${baseBranch}; cannot create a PR.`);
}

const diffStat = run("git", ["diff", "--stat", `${baseBranch}..HEAD`]).stdout.trim();
fs.writeFileSync(prBodyPath, renderBody({
  workflowName,
  taskName,
  branchName,
  baseBranch,
  runId,
  validation,
  e2e,
  implementationPlan,
  diffStat,
  commitCreated,
  commitSha
}), "utf8");

run("git", ["push", "-u", "origin", branchName]);

let pr = readExistingPr(branchName);
let created = false;
if (pr === null) {
  run("gh", ["pr", "create", "--base", baseBranch, "--head", branchName, "--title", prTitle, "--body-file", prBodyPath]);
  pr = readExistingPr(branchName);
  created = true;
} else {
  run("gh", ["pr", "edit", pr.url, "--title", prTitle, "--body-file", prBodyPath]);
  pr = readExistingPr(branchName);
}

if (pr === null) {
  throw new Error("PR was created or detected, but gh pr view did not return PR metadata.");
}

const result = {
  status: created ? "created" : "existing",
  title: prTitle,
  body_file: prBodyPath,
  branch_name: branchName,
  base_branch: baseBranch,
  commit_created: commitCreated,
  commit_sha: commitSha,
  pr,
  created_at: new Date().toISOString()
};

fs.writeFileSync(prJsonPath, `${JSON.stringify(result, null, 2)}\n`, "utf8");
fs.writeFileSync(prMdPath, renderPrMarkdown(result), "utf8");

function buildTitle(prefix, task) {
  return `${prefix}: ${task}`.slice(0, 120);
}

function renderBody(values) {
  const adr = values.implementationPlan?.adr;
  return [
    "## Summary",
    "",
    `- Workflow: ${values.workflowName}`,
    `- Task: ${values.taskName}`,
    `- Branch: ${values.branchName}`,
    `- Base: ${values.baseBranch}`,
    "",
    "## Changes",
    "",
    "```text",
    values.diffStat || "(no diff stat)",
    "```",
    "",
    "## Validation",
    "",
    `- Validation: ${values.validation?.status ?? "unknown"}`,
    `- E2E: ${values.e2e?.status ?? "unknown"}`,
    "",
    "## ADR",
    "",
    `- Required: ${adr?.required === true ? "yes" : "no"}`,
    ...(adr?.workspace_path ? [`- Path: ${adr.workspace_path}`] : []),
    "",
    "## Workflow Artifacts",
    "",
    "- handoff.md",
    "- validation.json",
    "- validation.md",
    "- e2e.json",
    "- e2e.md",
    "- e2e_fix_summary.md",
    "- implementation_summary.md",
    "- implementation_review.json",
    "",
    "## Notes",
    "",
    `- AWR run: ${values.runId}`,
    `- Workflow commit created by PR step: ${values.commitCreated ? "yes" : "no"}`,
    ...(values.commitSha ? [`- Commit: ${values.commitSha}`] : []),
    ""
  ].join("\n");
}

function renderPrMarkdown(result) {
  return [
    "# Pull Request",
    "",
    `- Status: ${result.status}`,
    `- Title: ${result.title}`,
    `- URL: ${result.pr.url ?? ""}`,
    `- Number: ${result.pr.number ?? ""}`,
    `- State: ${result.pr.state ?? ""}`,
    `- Branch: ${result.branch_name}`,
    `- Base: ${result.base_branch}`,
    `- Commit created: ${result.commit_created ? "yes" : "no"}`,
    ...(result.commit_sha ? [`- Commit: ${result.commit_sha}`] : []),
    ""
  ].join("\n");
}

function readExistingPr(headBranch) {
  const result = spawnSync("gh", ["pr", "view", "--head", headBranch, "--json", "number,url,title,state"], {
    cwd: workspaceDir,
    encoding: "utf8"
  });
  if (result.status !== 0) {
    return null;
  }
  return JSON.parse(result.stdout);
}

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function readJsonIfExists(file) {
  if (!fs.existsSync(file)) {
    return null;
  }
  return readJson(file);
}

function requiredField(object, field) {
  const value = object?.[field];
  if (typeof value !== "string" || value.trim() === "") {
    throw new Error(`${field} is required in branch.json`);
  }
  return value.trim();
}

function run(command, args) {
  const result = spawnSync(command, args, {
    cwd: workspaceDir,
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024
  });
  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} failed: ${result.stderr || result.stdout}`);
  }
  return {
    stdout: result.stdout ?? "",
    stderr: result.stderr ?? ""
  };
}

function requiredEnv(name) {
  const value = process.env[name];
  if (value === undefined || value === "") {
    throw new Error(`${name} is required`);
  }
  return value;
}
